"""The Day 1/2/3 notebooks are generated by scripts/build_kaggle_notebooks.py.

They share eight setup cells that have already needed fixing twice. Generated from one source,
a fix lands in all three or none; hand-edited, it lands in whichever one the editor had open.
This fails if a committed notebook differs from what the builder produces -- i.e. someone
edited the .ipynb directly, and the next rebuild would silently throw that edit away.

Fix: make the change in scripts/build_kaggle_notebooks.py, then run it.
"""

from __future__ import annotations

import importlib.util
import json
from pathlib import Path

import pytest

REPO_ROOT = Path(__file__).resolve().parents[1]


def _builder():
    path = REPO_ROOT / "scripts/build_kaggle_notebooks.py"
    spec = importlib.util.spec_from_file_location("build_kaggle_notebooks", path)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


BUILDER = _builder()


@pytest.mark.parametrize("name", sorted(BUILDER.NOTEBOOKS))
def test_committed_notebook_matches_the_builder(name: str) -> None:
    prefix, cells = BUILDER.NOTEBOOKS[name]
    expected = BUILDER.render(BUILDER.build(prefix, cells))
    actual = (REPO_ROOT / "notebooks" / name).read_text()
    assert actual == expected, (
        f"notebooks/{name} differs from scripts/build_kaggle_notebooks.py's output. Edit the "
        "builder, not the notebook, then run: python scripts/build_kaggle_notebooks.py"
    )


def test_the_shared_setup_cells_really_are_shared() -> None:
    """The point of the builder. If a day's notebook stopped using the shared objects, a fix
    to them would no longer reach it."""
    shared = [BUILDER.CLONE, BUILDER.INSTALL, BUILDER.DATASET, BUILDER.RESTORE,
              BUILDER.CACHE, BUILDER.FEDERATION]
    for name, (_, cells) in BUILDER.NOTEBOOKS.items():
        for cell in shared:
            assert cell in cells, f"{name} no longer includes a shared setup cell"


def test_every_fedaco_sweep_cell_calls_the_gate_guard_first() -> None:
    """The gate's fix lives in pyproject.toml inside ONE Kaggle session. A sweep cell that does
    not re-apply it runs on the broken default in every later session -- and a restart of the
    same notebook resets pyproject too. So every cell that launches a sweep other than the gate
    itself must call ensure_gate_fix() before its `!python` line."""
    for name, (_, cells) in BUILDER.NOTEBOOKS.items():
        for kind, source in cells:
            if kind != "code" or "run_sweep" not in source or "!python" not in source:
                continue
            if "gate_fitness.yaml" in source:
                continue  # the gate must run on the documented defaults, by design
            lines = source.splitlines()
            first_run = next(i for i, line in enumerate(lines) if line.startswith("!python"))
            assert any("ensure_gate_fix()" in line for line in lines[:first_run]), (
                f"{name}: a sweep cell launches without ensure_gate_fix() first:\n{source[:200]}"
            )


def test_the_guard_halts_rather_than_prints() -> None:
    """`!` failures do not stop Run-All. The guard must raise."""
    assert "raise RuntimeError" in BUILDER.FEDERATION[1]


def test_the_dataset_is_verified_by_content_not_just_by_name() -> None:
    """A re-versioned Kaggle dataset with the same filenames would pass a presence check."""
    source = BUILDER.DATASET[1]
    assert "hashlib.sha256" in source and "sha256" in source
    assert "raise RuntimeError" in source


def test_the_builder_output_is_deterministic() -> None:
    for name, (prefix, cells) in BUILDER.NOTEBOOKS.items():
        a = BUILDER.render(BUILDER.build(prefix, cells))
        b = BUILDER.render(BUILDER.build(prefix, cells))
        assert a == b, name
        ids = [c["id"] for c in json.loads(a)["cells"]]
        assert len(ids) == len(set(ids)), f"{name} has duplicate cell ids"
