"""The Day 1/2/3 notebooks are generated by scripts/build_kaggle_notebooks.py.

They share eight setup cells that have already needed fixing twice. Generated from one source,
a fix lands in all three or none; hand-edited, it lands in whichever one the editor had open.
This fails if a committed notebook differs from what the builder produces -- i.e. someone
edited the .ipynb directly, and the next rebuild would silently throw that edit away.

Fix: make the change in scripts/build_kaggle_notebooks.py, then run it.
"""

from __future__ import annotations

import importlib.util
import json
from pathlib import Path

import pytest

REPO_ROOT = Path(__file__).resolve().parents[1]


def _builder():
    path = REPO_ROOT / "scripts/build_kaggle_notebooks.py"
    spec = importlib.util.spec_from_file_location("build_kaggle_notebooks", path)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


BUILDER = _builder()


@pytest.mark.parametrize("name", sorted(BUILDER.NOTEBOOKS))
def test_committed_notebook_matches_the_builder(name: str) -> None:
    prefix, cells = BUILDER.NOTEBOOKS[name]
    expected = BUILDER.render(BUILDER.build(prefix, cells))
    actual = (REPO_ROOT / "notebooks" / name).read_text()
    assert actual == expected, (
        f"notebooks/{name} differs from scripts/build_kaggle_notebooks.py's output. Edit the "
        "builder, not the notebook, then run: python scripts/build_kaggle_notebooks.py"
    )


def test_the_shared_setup_cells_really_are_shared() -> None:
    """The point of the builder. If a day's notebook stopped using the shared objects, a fix
    to them would no longer reach it."""
    shared = [BUILDER.PREFLIGHT, BUILDER.CLONE, BUILDER.INSTALL, BUILDER.DATASET,
              BUILDER.RESTORE, BUILDER.CACHE, BUILDER.FEDERATION]
    for name, (_, cells) in BUILDER.NOTEBOOKS.items():
        for cell in shared:
            assert cell in cells, f"{name} no longer includes a shared setup cell"


def test_every_fedaco_sweep_cell_calls_the_gate_guard_first() -> None:
    """The gate's fix lives in pyproject.toml inside ONE Kaggle session. A sweep cell that does
    not re-apply it runs on the broken default in every later session -- and a restart of the
    same notebook resets pyproject too. So every cell that launches a sweep other than the gate
    itself must call ensure_gate_fix() before its `!python` line."""
    for name, (_, cells) in BUILDER.NOTEBOOKS.items():
        for kind, source in cells:
            if kind != "code" or "run_sweep" not in source or "!python" not in source:
                continue
            if "gate_fitness.yaml" in source:
                continue  # the gate must run on the documented defaults, by design
            lines = source.splitlines()
            first_run = next(i for i, line in enumerate(lines) if line.startswith("!python"))
            assert any("ensure_gate_fix()" in line for line in lines[:first_run]), (
                f"{name}: a sweep cell launches without ensure_gate_fix() first:\n{source[:200]}"
            )


def test_the_guard_halts_rather_than_prints() -> None:
    """`!` failures do not stop Run-All. The guard must raise."""
    assert "raise RuntimeError" in BUILDER.FEDERATION[1]


def test_the_dataset_is_verified_by_content_not_just_by_name() -> None:
    """A re-versioned Kaggle dataset with the same filenames would pass a presence check."""
    source = BUILDER.DATASET[1]
    assert "hashlib.sha256" in source and "sha256" in source
    assert "raise RuntimeError" in source


def test_the_builder_output_is_deterministic() -> None:
    for name, (prefix, cells) in BUILDER.NOTEBOOKS.items():
        a = BUILDER.render(BUILDER.build(prefix, cells))
        b = BUILDER.render(BUILDER.build(prefix, cells))
        assert a == b, name
        ids = [c["id"] for c in json.loads(a)["cells"]]
        assert len(ids) == len(set(ids)), f"{name} has duplicate cell ids"


def test_the_gpu_check_is_the_first_code_cell() -> None:
    """A wrong accelerator setting must fail in seconds, not after four minutes of installs --
    it is the one thing the user has to fix by hand, so they should find out first."""
    for name, (_, cells) in BUILDER.NOTEBOOKS.items():
        first_code = next(c for c in cells if c[0] == "code")
        assert first_code == BUILDER.PREFLIGHT, f"{name}: first code cell is not the GPU check"


def test_no_notebook_requires_attaching_the_dataset_by_hand() -> None:
    """A user ran Day 1 twice and stopped both times at 'no dataset attached'. The dataset cell
    must fetch it, and must not halt merely because /kaggle/input is empty."""
    source = BUILDER.DATASET[1]
    assert "locate_or_fetch_kaggle_dataset()" in source
    assert "if not inputs:" not in source, "the old halt-on-empty-input check is back"


def test_later_days_run_the_gate_themselves_when_its_results_are_missing() -> None:
    """Day 2 and Day 3 must not demand Day 1's output be attached: they re-run the gate."""
    for name in ("kaggle_day2_a1.ipynb", "kaggle_day3_main_and_robustness.ipynb"):
        cells = BUILDER.NOTEBOOKS[name][1]
        assert BUILDER.GATE_IF_MISSING in cells, name
        # ...and before any sweep that needs the fix
        first_sweep = next(i for i, (k, s) in enumerate(cells)
                           if k == "code" and "run_sweep" in s and "gate_fitness" not in s)
        assert cells.index(BUILDER.GATE_IF_MISSING) < first_sweep, name


def test_a_reclone_in_a_live_kernel_drops_stale_fedswarm_modules() -> None:
    assert "del sys.modules[name]" in BUILDER.CLONE[1]
